### PR TITLE
Accessibility-missing id for input

### PR DESCRIPTION
**Pull request by SA21**
@mukeshsoni
Please review this..PR..

Thanks!

### CODE REVIEW

**Comment by SA21** [comment]
I have made changes to the PR..as you requested...can you please review it...Thanks a lot!

**Comment by SA21** [comment]
I see that the object is being passed..but input element is not showing the id on it.What could be wrong?

**Comment by mukeshsoni** [comment]
Hmm, i think it's because id is not part of style! Sorry, might have lead you to the wrong path.

Can you trying going back to your earlier PR (but naming the prop `inputId` instead of `id`)?

**Comment by SA21** [comment]
@mukeshsoni  Adding props as id..worked for me..please review the changes...

**Comment by SA21** [comment]
Please review the changes

**Comment by SA21** [comment]
what can be the check here...
var idValue = this.props.inputId ? {id: this.props.inputId} : '';

pass this inside createElement('input', {idValue}); ........something like this...

**Comment by mukeshsoni** [comment]
Having empty string as the id is not a good solution IMO.

We can do 2 things here - 

1. Specify a default value for the prop in getDefaultProps method. Ensure that the default `inputId` value is sufficiently unique so that it doesn't clash with any other id of the app where it's used (`reactTelephoneInputUniqueId`?)

2. Pass an object with rest syntax ({...otherProps}) to the input element. That object will be empty by default but have the inputId, if provided by the user.

```
let otherProps = {}
if(this.props.inputId) {
  otherProps.id = this.props.inputId
}

<input
   onChange={this.handleInput}
   ...
   {...otherProps}
  />
```

**Comment by SA21** [comment]
Is this correct..

React.createElement('input', {
                onChange: this.handleInput,
                onClick: this.handleInputClick,
                onFocus: this.handleInputFocus,
                onBlur: this.handleInputBlur,
                onKeyDown: this.handleInputKeyDown,
                value: this.state.formattedNumber,
                ref: 'numberInput',
                type: 'tel',
                className: inputClasses,
                autoComplete: 'tel',
                placeholder: '+1 (702) 123-4567' }, ...otherProps),

**Comment by mukeshsoni** [comment]
We use JSX for the input element in the src file. Where did you find `React.createElement('input'..` ?

**Comment by SA21** [comment]
Sorry,i'm looking at the one inside /lib/ReactTelephoneInput.js..let me try in src one

**Comment by SA21** [comment]
another questions,when webpack is ran..will it automatically update the /lib/ReactTelephoneInput.js. file??

**Comment by mukeshsoni** [comment]
There is no webpack. The bundling is done using browserify. And yes, it should update the lib file.

**Comment by mukeshsoni** [comment]
I have merged the change. Would advice you a couple of things - 

1. If there is provision for writing tests in a repo, please write relevant tests
2. Please try to keep the code style aspects intact (like adding `{...otherProps}` to a new line).

Thanks for your efforts! Cheers!

**Comment by SA21** [comment]
Thanks a lot!!!

**Comment by aamohamm** [comment]
Hi, 
     Firstly Thanks for adding "inputId". Can you please update npm repository. It has code from Oct 17, so when i do a npm install it does get this new change "inputId".

**Pull request merged**
