### PR TITLE
Adding event onFocus

### PR DESCRIPTION
**Pull request by ematipico**
I am getting issues where there other components that include this component where the onFocus handler doesn't get the event as parameter. I'd like to add this feature

### CODE REVIEW

**Comment by mukeshsoni** [comment]
@ematipico what do you want to do with the event?

**Comment by ematipico** [comment]
Reading the target, for example. Access to the DOM element and doing other stuff. I think a SyntheticEvent should be always returned in order to not break other handler.

**Comment by neekey** [comment]
+1 for this feature, I have a form with multiple controls, each of which will have an instruction  present on the side when focus

**Comment by ematipico** [comment]
Friendly ping

**Pull request closed without merging**
