### PR TITLE
Support React 15

### PR DESCRIPTION
**Pull request by gbrassey**
This adds support for React 15. I've been using it and haven't had any issues.

I tried to update the tests as well but looks like they are broken from a previous change.

Thanks for this project 👍

### CODE REVIEW

**Comment by mukeshsoni** [comment]
updating react dependency to ^0.15.* will make it unusable with people having react 0.14.* or less. 

Will checkout the change for tests and merge.

**Comment by gbrassey** [comment]
It should be possible to support multiple versions of React. I've added v14 test utils so it can be tested with both versions. 

When you install just specify the version under test `npm install react@0.14.7 react-dom@0.14.7 react-addons-test-utils@0.14.7`.

**Comment by mukeshsoni** [comment]
I was talking about the peerdependencies requirement you have made in package.json. Doesn't that mean that anyone who installs this component would need to have at least v0.15.0 of react?

**Comment by gbrassey** [comment]
the `||` operator means that v14 and v15 will satisfy this libraries peerDependency so a user could have either one installed. 

```
  "peerDependencies": {
    "react": ">=0.14.0 || ^15.0.0",
    "react-dom": "^0.14.7 || ^15.0.0"
  },
```

**Comment by mukeshsoni** [comment]
Cool! Thanks @gbrassey

**Pull request merged**
