### PR TITLE
Add selectedCountry to onChange and onBlur

### PR DESCRIPTION
**Pull request by jaredsohn**

### CODE REVIEW

**Comment by jaredsohn** [comment]
The first commit shouldn't be a part of this PR; will remove it in a moment.

**Comment by jaredsohn** [comment]
All done until I get further feedback.  I cleaned up the commit, added some README changes, and verified that including the README code in the example works as expected.

**Comment by mukeshsoni** [comment]
Cool. Will verify and merge. Thanks!

**Comment by mukeshsoni** [comment]
Have merged and made a new release - 3.2.4. Thanks again @jaredsohn

**Pull request merged**
