### PR TITLE
Upgrade the component to ES6

### PR DESCRIPTION
**Pull request by madslundholmdk**
The component right now does not using ES6.
In React 15.5.x it's deprecated to use `React.createClass` - and in React 16 it will be removed.

This PR upgrades the component to use ES6 and ES6 classes instead of the `createClass`.

I have tested the code by using  `yarn run start` and tested the component.

It fix the issues #136 and #143. 

Future more I think the component should be refactored into separate components.

### CODE REVIEW

**Comment by mukeshsoni** [comment]
`createReactClass` will be moved to a different package (`create-react-class`) in react 16.x. We are already using the npm package `create-react-class`. It will have not issues with react 16.x.

**Comment by satishnath** [comment]
Just tested out the library (4.1.2) with react (16 RC) and it is fails `React.createClass is not a function`. Can you  double check?

**Comment by marcelorxaviers** [comment]
Just to check, are you guys still working on that PR? I'm using `react-telephone-input` on my company's project and while upgrading the React to 16.0.0 I had some issues with `React.createClass` and `React.PropTypes.string`:
```
...
var ReactTelephoneInput = React.createClass({
	    displayName: 'ReactTelephoneInput',
...
	    propTypes: {
	        value: React.PropTypes.string,
                 ...
            }
...
```

**Comment by mukeshsoni** [comment]
@marcelorxaviers @madslundholmdk  Yeah, need to use prop-types package. I think react-16 does not have PropTypes anymore

**Comment by mukeshsoni** [comment]
Oops, we already use the 'prop-types' package. Should not be a problem with react-16

**Comment by mukeshsoni** [comment]
@madslundholmdk here you go - ﻿﻿https://codesandbox.io/s/zwn0v61vxm

**Pull request closed without merging**
